### ISSUE TITLE
Could not get to work

### ISSUE THREAD

**Issue by mayerlench** [vinikira/netsuite-vue-boilerplate#2]
I could not get this to work.

I created a new app with their cli and ran npm build.
First of all if you look at the html file it builds, it clearly has relative paths of scripts that it need.

Either way im really interested in getting this working if you have a minute to talk about.
Would like to work on getting react too. Projects can be alot of fun if this can actually be implemented

**Comment by vinikira** [comment]
> I could not get this to work.
> I created a new app with their cli and ran npm build
>  First of all if you look at the html file it builds, it clearly has relative paths of scripts that it need.

There's a mistake in README, the right folder after build is **your_project/dist/** and not **your_project/build/** (fixed in https://github.com/vinikira/netsuite-vue-boilerplate/commit/073458b90485cf9bf0397bff2acedc1d1f9a8dde), but this does not interfere with anything. I looked at the generated html file and there's no script tag with src attribute.

Please, try again and let me know if worked.

**Comment by vinikira** [comment]
Close due to inactivity.
